apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: axon-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: axon-api
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 60